[package]
name = "mines_core"
version = "1.0.0"
edition = "2024"

[profile.release]
codegen-units = 1
lto = true
panic ="abort"
strip = "debuginfo"

[features]
godot = ["dep:godot"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
godot = {version = "0.5.3", optional = true, features = ["upcoming-editor-placeholders"]}
log = "0.4.29"
rand = "0.10.1"

[dev-dependencies]
env_logger = "0.11.10"
