use log::info;
use mines_core::core::{
    generator::{Generator, st::StGenerator},
    solver::{Solver, st::StSolver},
    state::{BoardInterface, Visibility, grid::Board},
};
use rand::{SeedableRng, rngs::StdRng};

/// Construct a grid from string, with `*` as mines and other characters as open cells
fn grid_from_ascii(grid: &[&str], start: (usize, usize)) -> Board {
    let height = grid.len();
    let width = grid[0].len();
    let mut map = Vec::with_capacity(width * height);

    for r in grid {
        for ch in r.chars() {
            map.push(ch == '*');
        }
    }

    Board::from_mines(width, height, start, map)
}

/// Tests for solving of a grid generated by Simon Thatham's mines.c. This does not check for
/// advanced constraint resolution (> 2 Constraints).
#[test]
fn test_solver() {
    env_logger::try_init().unwrap_or_default();
    let map = [
        "*...*...*",
        "**.***..*",
        "*....*...",
        "**......*",
        "**....**.",
        "***...***",
        "...*.*..*",
        "*...*...*",
        ".***...**",
    ];
    let num_mines = 35;
    let mut grid = grid_from_ascii(&map, (4, 4));
    // let map = [
    //     "...**.*.*.****...*......*******.",
    //     ".*..*....*..*..*....***.****....",
    //     "**.......*.....*..*...***.***.**",
    //     "*****..*.*.....****..*.*.*..**..",
    //     "**.**......*..*......**.........",
    //     "...*.***..***..*.*.*...*..***...",
    //     "..****....*.***....**....**.....",
    //     ".*...*....**...*.*..*..*.**..*..",
    //     "....***....*........*..***...**.",
    //     "...*......**...*.*.***....**..*.",
    //     "...*..*...***.....***.*.*.....*.",
    //     ".**..*...***.....*...........**.",
    //     ".*...****..*...*.*........*.....",
    //     ".*.****..*....***.**.*....*..**.",
    //     "******..*.*......*.*.....**...**",
    //     "******..***...*..***..***...**.*",
    // ];
    // let num_mines = 200;
    // let mut grid = grid_from_ascii(&map, (10, 8));
    StSolver::solve(&mut grid).unwrap_or_else(|_| {
        panic!("Solving failed after generation. Partially solved: {grid}");
    });
    println!("Grid: {grid}");
    assert_eq!(
        grid.count_cells(Visibility::Hidden),
        0,
        "Number of hidden cells {} > 0.",
        grid.count_cells(Visibility::Hidden)
    );
    assert_eq!(
        grid.count_cells(Visibility::Flagged),
        num_mines,
        "Number of flagged cells {} != {num_mines}",
        grid.count_cells(Visibility::Flagged)
    );
}

#[test]
fn test_generator() {
    env_logger::try_init().unwrap_or_default();
    let mut rng = StdRng::seed_from_u64(2837489); // 1234
    let width = 32;
    let height = 16;
    let start = (width / 2, height / 2);
    let num_mines = 200;
    let mut board = Board::new_random(width, height, start, &mut rng, num_mines);

    let mut generator = StGenerator::new(&mut board, 500);
    let num_perturbs = generator
        .generate::<StSolver<Board>>(start, &mut rng)
        .expect("Failed board generation.");
    info!("Generated grid in {num_perturbs} perturbations: {board:?}");

    let mut board2 = board.clone();
    board2.reset(start);
    StSolver::solve(&mut board2).unwrap_or_else(|_| {
        panic!("Solving failed after generation. Partially solved: {board2}");
    });
    info!("Aftering solving: {board2:?}");
    assert_eq!(
        board2.count_cells(Visibility::Hidden),
        0,
        "Number of hidden cells {} > 0.",
        board2.count_cells(Visibility::Hidden)
    );
    assert_eq!(
        board2.count_cells(Visibility::Flagged),
        num_mines,
        "Number of flagged cells {} != {num_mines}",
        board2.count_cells(Visibility::Flagged)
    );
}
