use mines_core::core::{
    solver::{Solver, SolverOptions, st::StSolver},
    state::{Visibility, grid::Board},
};

/// Construct a grid from string, with `*` as mines and other characters as open cells
fn grid_from_ascii(grid: &[&str], start: (usize, usize)) -> Board {
    let height = grid.len();
    let width = grid[0].len();
    let mut map = Vec::with_capacity(width * height);

    for r in grid {
        for ch in r.chars() {
            map.push(ch == '*');
        }
    }

    Board::from_mines(width, height, start, map)
}

/// Tests for solving of a grid generated by Simon Thatham's mines.c. This does not check for
/// advanced constraint resolution (> 2 Constraints).
#[test]
fn test() {
    env_logger::try_init().unwrap_or_default();
    let map = [
        "*...*...*",
        "**.***..*",
        "*....*...",
        "**......*",
        "**....**.",
        "***...***",
        "...*.*..*",
        "*...*...*",
        ".***...**",
    ];
    let num_mines = 35;
    let mut grid = grid_from_ascii(&map, (4, 4));
    StSolver::new(&mut grid, SolverOptions::default()).expect("Failed to solve grid.");
    println!("Grid: {grid}");
    assert_eq!(
        grid.count_cells(Visibility::Hidden),
        0,
        "Number of hidden cells {} > 0.",
        grid.count_cells(Visibility::Hidden)
    );
    assert_eq!(
        grid.count_cells(Visibility::Flagged),
        num_mines,
        "Number of flagged cells {} != {num_mines}",
        grid.count_cells(Visibility::Flagged)
    );
}
